### ISSUE TITLE
Typo v Tag entitě

### ISSUE THREAD

**Issue by wodCZ** [ondraondra81/demoblog#1]
Ahoj,

v Tag entitě máš podle mě překlep - addArticle**s**.

Nechci být rejpal, ale vzhledem k tomu že to píšeš na blog pro lidi co s tím začínají, tak připomínkuju - mohlo by to někoho zmást.

https://github.com/ondraondra81/demoblog/blob/master/app/Model/Entities/Tag.php#L77

**Comment by ondraondra81** [comment]
Díky, opraveno
